import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SplashScreen from "@/components/ui/SplashScreen";

const supreme = localFont({
  src: "../../public/fonts/Supreme-Variable.ttf",
  variable: "--font-display",
});

const poppins = localFont({
  src: "../../public/fonts/Poppins-Variable.ttf",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${supreme.variable} ${poppins.variable} bg-background font-sans leading-6 text-foreground antialiased`}
      >
        <SplashScreen>{children}</SplashScreen>
        <script
          src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossOrigin="anonymous"
          async
          defer
        />
      </body>
    </html>
  );
}
