import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const supreme = localFont({
  src: "/../../public/fonts/Supreme-Variable.ttf",
  variable: "--font-display",
});

const poppins = localFont({
  src: "/../../public/fonts/Poppins-Variable.ttf",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${supreme.variable} ${poppins.variable} bg-background font-sans leading-6 text-foreground antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
